const menu = document.querySelector('.menu-toggle');
const navigation = document.querySelector('#navigation');
function closeMenu(){menu.setAttribute('aria-expanded','false');navigation.classList.remove('open')}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));navigation.classList.toggle('open',open)});
navigation.addEventListener('click',e=>{if(e.target.closest('a,button'))closeMenu()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&navigation.classList.contains('open')){closeMenu();menu.focus()}});
if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.remove('pending');observer.unobserve(entry.target)}})},{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>{if(el.getBoundingClientRect().top>innerHeight){el.classList.add('pending');observer.observe(el)}})}
const content={about:`<p class="eyebrow">About Monark</p><h2 id="dialog-title">Built for the UAE. Connected globally.</h2><p>Monark International LLC FZ is a UAE-based trading business with expertise in container trading, sales and supply, rental and leasing, global sourcing, and logistics coordination.</p><p>Share your requirements with the team to discuss container type, quantity, condition, intended use, and location.</p><a class="button" href="mailto:info@monark.ae">Talk to Monark →</a>`,
faq:`<p class="eyebrow">FAQ</p><h2 id="dialog-title">Frequently asked questions</h2><details open><summary>Can I buy or rent a container?</summary><p>Monark provides container sales and rental options. Share your intended use, location and required duration so the team can discuss suitable options and availability.</p></details><details><summary>Which container types are available?</summary><p>The range includes standard dry, high cube, reefer, open top and flat rack containers. Ask the team to confirm the size, condition and availability for your requirement.</p></details><details><summary>Do you arrange transportation?</summary><p>Monark coordinates container delivery and transportation across the UAE. Share your delivery location to discuss access and arrangements.</p></details><details><summary>Can I rent for a short period?</summary><p>Short-term and long-term rental requirements can be discussed with the team. Availability and rental terms depend on your requirement.</p></details><details><summary>How do I request a quote?</summary><p>Email info@monark.ae or call +971 55 205 2260 with the container type, quantity, location and whether you want to buy or rent.</p></details><a class="button" href="mailto:info@monark.ae">Contact Monark →</a>`,
resources:`<p class="eyebrow">Container resources</p><h2 id="dialog-title">Start with your requirement.</h2><p>To help the team discuss suitable container options, prepare these details:</p><ul><li>Container type and preferred size</li><li>Quantity and required condition</li><li>Purchase or rental, including rental duration</li><li>Intended use and delivery location</li><li>Your preferred availability date</li></ul><a class="button" href="mailto:info@monark.ae?subject=Container%20options">Discuss your options →</a>`,
privacy:`<h2 id="dialog-title">Privacy Policy</h2><p>The final company privacy policy has not been supplied yet. This Home page preview does not include analytics or a submission database. Email links open your email application.</p>`,
terms:`<h2 id="dialog-title">Terms of Service</h2><p>The final company terms have not been supplied yet. Please contact Monark to confirm availability, pricing, rental terms and transportation arrangements for your requirement.</p>`
};
const dialog=document.querySelector('#info-dialog');let opener;
document.querySelectorAll('[data-dialog]').forEach(button=>button.addEventListener('click',()=>{opener=button;document.querySelector('#dialog-content').innerHTML=content[button.dataset.dialog];dialog.showModal()}));
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
dialog.addEventListener('close',()=>opener?.focus());

